### ISSUE TITLE
Connexion CAS à moitié

### ISSUE THREAD

**Issue by FloChehab** [danousna/lefil#6]
Salut,

Je me demandais la raison derrière le fait d'avoir fait une connexion CAS mais qu'à moitié ? (On doit quand même créer un utilisateur)
C'est pour faciliter la gestion des utilisateurs extérieurs ?

Super site sinon !

**Comment by danousna** [comment]
Merci du retour ! 

J’aurai pu faire une connexion CAS « complète » dans le sens où quand l’utilisateur s’inscris et donc doit se logger au CAS, le site créé automatiquement un utilisateur avec les infos du CAS. Mais je voulais laisser la possibilité à l’utilisateur de modifier ses infos (du genre son pseudo) avant qu’il soit inscrit. Dans tous les cas, l’inscription est possible que si l’utilisateur est authentifié par le CAS.

De toute façon, pour les sites qui passent par un CAS pour vérifier l’acces seulement à certaines personnes (ici les étudiants utc) sont tous obligés de rajouter leur propre système de gestion utilisateurs vu que le CAS renvoie peu d’infos.

**Comment by FloChehab** [comment]
Ok pour le retour. J’ai tendance à voir le CAS comme un moyen d’authentification centralisé : il renvoie suffisement d’informations pour définir un utilisateur. Après c’est sûr qu’en général il faut rajouter des infos supplémentaires.
